const crypto = require('crypto');

class WatermarkService {
  generateWatermark(data, userId, theoryId) {
    const watermark = {
      id: crypto.randomUUID(),
      userId,
      theoryId,
      timestamp: new Date().toISOString(),
      hash: this.createHash(data, userId, theoryId)
    };

    return {
      ...data,
      _watermark: watermark,
      _attribution: `Generated by 3rd-Eye-View | User: ${userId} | Theory: ${theoryId} | ${watermark.timestamp}`
    };
  }

  createHash(data, userId, theoryId) {
    const content = JSON.stringify(data) + userId + theoryId;
    return crypto.createHash('sha256').update(content).digest('hex').substring(0, 16);
  }

  verifyWatermark(data) {
    if (!data._watermark) return { valid: false, reason: 'No watermark found' };

    const expectedHash = this.createHash(
      { ...data, _watermark: undefined, _attribution: undefined },
      data._watermark.userId,
      data._watermark.theoryId
    );

    return {
      valid: expectedHash === data._watermark.hash,
      watermark: data._watermark
    };
  }

  trackUsage(watermarkedData, context) {
    if (!watermarkedData._watermark) return null;

    const usage = {
      watermarkId: watermarkedData._watermark.id,
      userId: watermarkedData._watermark.userId,
      theoryId: watermarkedData._watermark.theoryId,
      usedIn: context.location,
      usedBy: context.organization,
      usedFor: context.purpose,
      timestamp: new Date().toISOString()
    };

    console.log('WATERMARK USAGE TRACKED:', usage);
    return usage;
  }
}

module.exports = new WatermarkService();